### ISSUE TITLE
access request

### ISSUE THREAD

**Issue by CaullenOmdahl** [kirchner-trevor/NW_Market_OCR#1]

**Comment by kirchner-trevor** [comment]
Hi, if you can leave me your Discord or Reddit username I will send you credentials!

**Comment by CaullenOmdahl** [comment]
Yeah, of course. I wasn't sure what you needed. I'm Real_Kiwi#3843 on discord.

**Comment by kirchner-trevor** [comment]
Key sent over Discord!
