### ISSUE TITLE
Access Request

### ISSUE THREAD

**Issue by obijuankenoi** [kirchner-trevor/NW_Market_OCR#4]
Discord: ObiJuanKenoi#8590

**Comment by kirchner-trevor** [comment]
Hey! I've sent you a friend request on Discord to send you a key :)

**Comment by obijuankenoi** [comment]
Hi Trevor, my apologies. I might have ignored the friend request. There
were some scams going around and random friend requests so I decided to
ignore them all.
Can you send me the credentials via email?

**Comment by kirchner-trevor** [comment]
GitHub doesn't share your email, so if you can share that I can sent it over email. Otherwise I re-sent the Discord friend request. I am Tobius#3172. You can also join the discord server, which would allow me to message your if you'd rather do that. https://discord.gg/ZdcRn89JtU

**Comment by kirchner-trevor** [comment]
Credentials sent over Discord.
